@REM This script allows a 3rd party IDE to use CyElfTool to perform
@REM the post processing that is necessary to update the *.elf file
@REM generated by the linker into a complete memory image to use in
@REM programming the PSoC.
@REM NOTE: This script is auto generated. Do not modify.
set buildDir=%PWD%
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
chdir /d ..\.\Export
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
CyElfTool.exe -C "%~1" --flash_row_size 256 --flash_size 262144 
@IF %errorlevel% NEQ 0 EXIT /b %errorlevel%
